# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  nix: eld/nix@1.0.0

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - nix/install
      - checkout
      - run:
          name: "Build"
          command: "nix-build default.nix"
workflows:
  example-workflow:
    jobs:
      - example-job